USE ${hiveconf:ORCDBNAME};

ANALYZE TABLE nation COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE region COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE supplier COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE part COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE partsupp COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE orders COMPUTE STATISTICS FOR COLUMNS;
ANALYZE TABLE lineitem COMPUTE STATISTICS FOR COLUMNS;
